language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - cd frontend && yarn install && ../backend && yarn install && ../ && yarn test
# on:
# branch: master
